<?php

namespace Database\Seeders;

use App\Models\Teacher;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* Teacher::create([
            'CI' => '28544285',
            'name' => 'Alexis',
            'lastname' => 'Gonzalez',
            'area_id' => 1,
            'phone' => '04127609320',
            'home_phone' => '',
            'email' => 'alberto@email.com',
            'adress' => 'Las Mercedes, Calle San Luis',
            'state_id' => 1,
            'municipy_id' => 1,
        ]); */

        $teachers = [
            ['CI' => 16407820,'name' => 'Alberto','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17062851,'name' => 'Aholimar','lastname' => 'Hernandez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Mireya','lastname' => 'De Reinoso','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13150395,'name' => 'Eduardo','lastname' => 'Avila','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Mariuxy','lastname' => 'Martinez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15712263,'name' => 'Omar','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8642883,'name' => 'Cesar','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7290984,'name' => 'Eder','lastname' => 'Buitrago','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13874957,'name' => 'Ankises','lastname' => 'Garcia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17253708,'name' => 'Luis','lastname' => 'Alvarado','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Shirley','lastname' => 'Suarez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12842395,'name' => 'Adriana','lastname' => 'Urbaez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15998858,'name' => 'Carlos','lastname' => 'Camejo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16804257,'name' => 'Liliana','lastname' => 'Alcala','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12840963,'name' => 'Susana','lastname' => 'De Farias','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17062359,'name' => 'Joali','lastname' => 'Medina','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15710746,'name' => 'Yaurimar','lastname' => 'Escobar','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7280730,'name' => 'Ramon','lastname' => 'Ramirez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13811476,'name' => 'Elizabeth','lastname' => 'Cusati','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 3221246,'name' => 'Priscila','lastname' => 'Oribuenes','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11976054,'name' => 'Jhonny','lastname' => 'Gabazutt','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10669069,'name' => 'Luisa','lastname' => 'Chira','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14142964,'name' => 'Wilmer','lastname' => 'Subero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10672405,'name' => 'Francisco','lastname' => 'Cordero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7297740,'name' => 'Pedro','lastname' => 'Cabeza','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9036837,'name' => 'Nidia','lastname' => 'Melo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13354353,'name' => 'Sofia','lastname' => 'Nasuti','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9886372,'name' => 'Guisseppe','lastname' => 'Schembari','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12447394,'name' => 'David','lastname' => 'Lazo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Jesus','lastname' => 'Torres','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16803078,'name' => 'Guillermo','lastname' => 'Aranguren','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15393154,'name' => 'Maria','lastname' => 'Yanez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Valdemar','lastname' => 'Flores','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 4391735,'name' => 'Carlos','lastname' => 'Hernandez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Nancy','lastname' => 'Urrueta','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Luis','lastname' => 'Torres','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Alannys','lastname' => 'Ramos','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17062182,'name' => 'Yoan','lastname' => 'Vasquez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17950758,'name' => 'Javier','lastname' => 'De La Rosa','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11115389,'name' => 'Rosaris','lastname' => 'Bustamante','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10674498,'name' => 'Alberto','lastname' => 'De Sousa','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Rafael','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11365827,'name' => 'Miguel','lastname' => 'Ferrer','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15712380,'name' => 'Gabriela','lastname' => 'Torres','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10522288,'name' => 'Antonieta','lastname' => 'Petrone','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11117237,'name' => 'Yusara','lastname' => 'Reina','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9884687,'name' => 'Luz','lastname' => 'Franco','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Jobanny','lastname' => 'Garcia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12210356,'name' => 'Mariyen','lastname' => 'Ojeda','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9883586,'name' => 'Edgar','lastname' => 'Tovar','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9654824,'name' => 'Yelitza','lastname' => 'Torrealba','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12030464,'name' => 'Jorge','lastname' => 'España','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8682690,'name' => 'Millard','lastname' => 'Escalona','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11119269,'name' => 'Omar','lastname' => 'Rivas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7178546,'name' => 'Eduardo','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11116590,'name' => 'Genniberth','lastname' => 'Reinoso','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Gustavo','lastname' => 'Fonseca','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12927226,'name' => 'Mirelys','lastname' => 'Diaz','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13811313,'name' => 'Rafael','lastname' => 'Carrasquel','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13576526,'name' => 'Karina','lastname' => 'Hernandez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14395039,'name' => 'Isbely','lastname' => 'Moreno','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14147067,'name' => 'Oswaldo','lastname' => 'Montaño','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12346776,'name' => 'Josmar','lastname' => 'Dugarte','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7225603,'name' => 'Evelin','lastname' => 'Fernandez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 5621308,'name' => 'Diogenes','lastname' => 'Alvarez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10058718,'name' => 'Adolfo','lastname' => 'Molina','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17063158,'name' => 'Edith','lastname' => 'Hernandez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8620395,'name' => 'Antonio','lastname' => 'Guerrero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18316760,'name' => 'Simon','lastname' => 'Torrealba','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Hector','lastname' => 'Torrealba','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7225216,'name' => 'Marisela','lastname' => 'Trujillo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12737448,'name' => 'Miguel','lastname' => 'Hernandez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9883116,'name' => 'Nubia','lastname' => 'Tamiche','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15145270,'name' => 'Ysnaldo','lastname' => 'Garcia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 6331034,'name' => 'Jairo','lastname' => 'Molina','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12129641,'name' => 'William','lastname' => 'Cortez','area_id' => 1,'phone' => '0416-9840180','home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13732719,'name' => 'Miguel','lastname' => 'Flores','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Manuel','lastname' => 'Martinez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7232097,'name' => 'Leonel','lastname' => 'Jimenez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11123298,'name' => 'Douglas','lastname' => 'Ruiz','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18473115,'name' => 'Simon','lastname' => 'Sanchez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Emilio','lastname' => 'Silveira','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Erika','lastname' => 'Orta','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Javier','lastname' => 'Arevalo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17272361,'name' => 'Monica','lastname' => 'Benitez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16044450,'name' => 'Ruben','lastname' => 'Silverio','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13448405,'name' => 'Daily','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13239942,'name' => 'Carlos','lastname' => 'Torcatt','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13732279,'name' => 'Johan','lastname' => 'Guevara','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Argenis','lastname' => 'Mendoza','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13942164,'name' => 'Luis Daniel','lastname' => 'Mendez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Luis','lastname' => 'Gonzalez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17374517,'name' => 'Freddy','lastname' => 'Martinez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14395213,'name' => 'Gregory','lastname' => 'Sanchez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Jose','lastname' => 'Armada','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18327135,'name' => 'Felix','lastname' => 'Galindo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9883255,'name' => 'Miguel','lastname' => 'Padron','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15031487,'name' => 'Jellymar','lastname' => 'Dugarte','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Maria','lastname' => 'Colicchio','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Maibelin','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14219273,'name' => 'Luheris','lastname' => 'Salas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18231287,'name' => 'Nelissa','lastname' => 'Moleiro','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Daniel','lastname' => 'Cardenas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16132256,'name' => 'Alfredo','lastname' => 'Sanchez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Edgar','lastname' => 'Rattia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Edward','lastname' => 'Del Corral','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Fran Jose','lastname' => 'Garcia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14643607,'name' => 'Erick','lastname' => 'Siso','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16364548,'name' => 'Gueyby','lastname' => 'Toro','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8815602,'name' => 'Elsi','lastname' => 'Valenzuela','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9434518,'name' => 'Ylvis','lastname' => 'Romero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Yoletzi','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Araceli','lastname' => 'Mendoza','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13150002,'name' => 'Wilmer','lastname' => 'Caldera','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Mailen','lastname' => 'Cerezo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16362077,'name' => 'Cesar','lastname' => 'Montilla','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13942326,'name' => 'Dionis','lastname' => 'Marcano','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11119750,'name' => 'Adriana','lastname' => 'Laya','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17165081,'name' => 'Jose','lastname' => 'Guillen','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11123626,'name' => 'Betania','lastname' => 'Belisario','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14146363,'name' => 'Adrienne','lastname' => 'Rangel','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16074823,'name' => 'Jomar','lastname' => 'Matos','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12608964,'name' => 'Jose','lastname' => 'Blanco','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11119966,'name' => 'Leopoldo','lastname' => 'Arvelaiz','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13492948,'name' => 'Jenny','lastname' => 'Reyes','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 21759887,'name' => 'Cora','lastname' => 'Gerbi','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14871579,'name' => 'Gonzalo','lastname' => 'Yanez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11118853,'name' => 'Wilmer','lastname' => 'Vanezca','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16074594,'name' => 'Caleb','lastname' => 'Betancourt','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Marcos','lastname' => 'Mena','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12343344,'name' => 'Carlos','lastname' => 'Ramos','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 4391319,'name' => 'Ingrid','lastname' => 'Nederr','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15082537,'name' => 'Maria Jose','lastname' => 'Jaramillo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9438276,'name' => 'Johyce','lastname' => 'Navas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14147500,'name' => 'Maria','lastname' => 'Diaz','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16075844,'name' => 'Luis','lastname' => 'Cerezo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10665408,'name' => 'Joel','lastname' => 'Gomez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15711922,'name' => 'Alexander','lastname' => 'Rios','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16207573,'name' => 'Mariandreina','lastname' => 'Simonelli','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12737527,'name' => 'Mar-y-ces','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15527692,'name' => 'Jose','lastname' => 'Medina','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14643886,'name' => 'Reinaldo','lastname' => 'Vargas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16552619,'name' => 'Edgar','lastname' => 'Palomares','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Ada','lastname' => 'Virguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16790608,'name' => 'Maria','lastname' => 'Magallanes','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13576764,'name' => 'Jonathan','lastname' => 'Gomez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18895623,'name' => 'Virginia','lastname' => 'Castellano','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15823037,'name' => 'Luis','lastname' => 'Malave','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11116504,'name' => 'Yuseth','lastname' => 'Palacio','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Rosanna','lastname' => 'Rojas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Omar','lastname' => 'Godoy','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17200598,'name' => 'Maria','lastname' => 'Lovera','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13732739,'name' => 'Mary','lastname' => 'Sojo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16074889,'name' => 'Analis','lastname' => 'Brito','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11413849,'name' => 'Rafael','lastname' => 'Mendoza','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Dionicio','lastname' => 'Buitrago','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Yessica','lastname' => 'Marcano','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15712760,'name' => 'Alexmir','lastname' => 'Briceño','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Yaletza','lastname' => 'Bolivar','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 9915039,'name' => 'Marisol','lastname' => 'Quianes','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17352953,'name' => 'Jose G.','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Maria','lastname' => 'Padron','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 19473305,'name' => 'Celso','lastname' => 'Marquez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Daily','lastname' => 'Silva','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11123596,'name' => 'Jenny','lastname' => 'Padilla','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 19473280,'name' => 'Elso','lastname' => 'Marquez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12309956,'name' => 'Naileth','lastname' => 'Corro','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18803696,'name' => 'Francisco','lastname' => 'Guedez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16074998,'name' => 'Pedro','lastname' => 'Quintero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11121831,'name' => 'Argel','lastname' => 'Barrios','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10672857,'name' => 'Jenny','lastname' => 'Paez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11120574,'name' => 'Francis','lastname' => 'Ron','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14395041,'name' => 'Lupe','lastname' => 'Padron','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14573015,'name' => 'Elian','lastname' => 'Carrillo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10665516,'name' => 'Flor Ana','lastname' => 'Bolivar','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13875381,'name' => 'Betzabe','lastname' => 'Ledezma','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8995563,'name' => 'Zobeida','lastname' => 'Ortega','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7276561,'name' => 'Yolanda','lastname' => 'Colmenares','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 4313662,'name' => 'Alexy','lastname' => 'Rosales','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Anny','lastname' => 'Barrios','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Maruja','lastname' => 'Toro','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8996811,'name' => 'Tibisay','lastname' => 'Duarte','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Hector','lastname' => 'Arias','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10666800,'name' => 'Leonardo','lastname' => 'Romero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16075508,'name' => 'Michele','lastname' => 'Sanchez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15610270,'name' => 'Adriana','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Reina','lastname' => 'Colmenares','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Yannely ','lastname' => 'Yajurez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Lesbia','lastname' => 'García','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Pablo ','lastname' => 'Velasquez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11116120,'name' => 'Wendis','lastname' => 'Cordero','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Sección','lastname' => 'Cerrada','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8233119,'name' => 'Tania ','lastname' => 'Lopez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18044586,'name' => 'Carlos','lastname' => 'Ruiz','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16346601,'name' => 'Soleidy','lastname' => 'Peña','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 12361346,'name' => 'Yusmary ','lastname' => 'Vidal','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8351129,'name' => 'Florencio','lastname' => 'Carreño','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 10670590,'name' => 'Juan Carlos','lastname' => 'Barrios','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Alfonso','lastname' => 'Chirguita','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 6054849,'name' => 'Argenis A','lastname' => 'Mendoza','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Karelis','lastname' => 'Salas','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 20363511,'name' => 'Dehivis','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17609887,'name' => 'Barmis Paola','lastname' => 'Zarate','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 13447505,'name' => 'Yaluimar','lastname' => 'Willians','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Maikor','lastname' => 'Maita','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16804634,'name' => 'Thruman ','lastname' => 'Rebolledo','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Alejandro','lastname' => 'Garcia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8781966,'name' => 'Teodoro','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18444238,'name' => 'Roberto','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15393178,'name' => 'Jose ','lastname' => 'Montes','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16364063,'name' => 'Jackson','lastname' => 'Garcia','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11115534,'name' => 'Oswaldo','lastname' => 'Arana','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 19725444,'name' => 'Gabriel Alfredo','lastname' => 'Díaz Boyer','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 15712251,'name' => 'Yosmar del Valle','lastname' => 'Ruíz Requena','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18804343,'name' => 'Carlos Jose','lastname' => 'Covis Gomez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Yorman','lastname' => 'Palacio','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11999285,'name' => 'Elida','lastname' => 'Ibarra','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17433513,'name' => 'Richard','lastname' => 'Pachano','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16362255,'name' => 'Alberto R.','lastname' => 'Véliz E.','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 14745710,'name' => 'Merly','lastname' => 'Orta','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 20877147,'name' => 'Norberto','lastname' => 'Castro','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Jose','lastname' => 'Rodriguez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17352881,'name' => 'Seijas','lastname' => 'Carvic','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 18803055,'name' => 'Cesar','lastname' => 'Carpio','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 16804622,'name' => 'Tomas','lastname' => 'Flores','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 19473159,'name' => 'Jhonatan','lastname' => 'Ramirez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11683843,'name' => 'Eglis','lastname' => 'Blanco','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 7274157,'name' => 'Hector','lastname' => 'Torrealba','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 17165081,'name' => 'Jose','lastname' => 'Guillen','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 0,'name' => 'Francisco','lastname' => 'Delgado','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 11120718,'name' => 'Mildred ','lastname' => 'Perez','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
            ['CI' => 8617812,'name' => 'Noraima de Jesus','lastname' => 'Guerrero Quintana','area_id' => 1,'phone' => 0, 'home_phone' => '','email' => 0,'adress' => '','state_id' => 0, 'municipy_id' => 0],
        ];

        Teacher::insert($teachers);
    }
}
